sudo: required
language: python
python:
    - "3.5"
services:
    - docker
before_install:
    - docker build -t dollar-tracker .

script:
    - docker run dollar-tracker /bin/sh -c "py.test /usr/src/app/dollar-tracker/tests"


